title: Michael Kingston # your name (or website title) here
logo: "/images/passo de stelvio.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Data Science Portfolio<b>
  <ul>
    <li>Analysis of the Palm Olein and Vegetable oil global market</li>
    <li></li>
    <li></li>
  <br><br>
  Kaggle Competitions
    <li>Petfinder.my Pawpularity contest (top 8%, broze medal)</li>
    <li>NBME - Score Clinical Patient Notes (top 26%)</li>
    <li>Feedback Prize: evaluating student writing (top 28%)</li>
  <br><br>
  <a href="https://www.linkedin.com/in/michael-kenneth-kingston/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
